### ISSUE TITLE
Unable to use faster-whisper

### ISSUE THREAD

**Issue by ayancey** [ahmetoner/whisper-asr-webservice#101]
Hi,

I'm testing faster-whisper support and I'm having trouble with it. I'm running speed tests and am getting very similar speeds when trying both OpenAI and faster-whisper. Can anyone confirm if they're having good luck with it or running into issues like I am?

Thanks,
Alex

**Comment by ahmetoner** [comment]
Tomorrow we will have new release for this and gpu issue.

**Comment by ahmetoner** [comment]
Hi @ayancey,

Could you please test `debug` image to verify Faster Whisper works correctly?

For CPU:

```sh
docker run -d -p 9000:9000 -e ASR_MODEL=base -e ASR_ENGINE=faster_whisper onerahmet/openai-whisper-asr-webservice:debug
```

For GPU:

```sh
docker run -d --gpus all -p 9000:9000 -e ASR_MODEL=base -e ASR_ENGINE=faster_whisper onerahmet/openai-whisper-asr-webservice:debug-gpu
```

**Comment by ayancey** [comment]
I tested this, and it doesn't appear to be much faster using base model on a GPU with a 22 minute audio file. There could be something wrong with my testing methodology though. Keep up the good work!

**Comment by MrSaiclops** [comment]
Hmmm, I seem to be experiencing the same thing with base model on CPU. About eight minutes for a 45 minute episode. (Running through Bazarr.)
