### ISSUE TITLE
Failed to load audio

### ISSUE THREAD

**Issue by eeric** [ahmetoner/whisper-asr-webservice#104]
poetry run gunicorn --bind 10.12.16.110:9000 --timeout 0 app.webservice:app -k uvicorn.workers.UvicornWorker

RuntimeError: Failed to load audio: ffmpeg: /home/yangqi/anaconda3/lib/libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)

**Comment by whiteadam** [comment]
Do you have `ffmpeg` installed?

**Comment by ayancey** [comment]
What is your ffmpeg version?
