### ISSUE TITLE
File format for client requests

### ISSUE THREAD

**Issue by jptrsn** [ahmetoner/whisper-asr-webservice#106]
I am attempting to send an audio recording from the client directly to the whisper container's /asr endpoint. I have tried sending the data as a string in a few different ways, but it always returns me a `422: unprocessable entity` error.

I have captured the audio into a blob from a media stream. I then have the blob data, and I attempt to convert it into the format that whisper is expecting (noted as `string($binary)` in the docs). However, no matter what format I attempt to use to encode the data, it returns me the same error.

For example, for the given blob data provided as `data`, I have tried using:
* The results from the call to `data.text()`,
* Reading the blob using a `FileReader` and returning the results:
** (in the example below, I have tried both the pure data string, as well as the entire URL)
```
return new Promise((res, rej) => {
      const reader = new FileReader();
      reader.readAsDataURL(data)
      reader.onloadend = (event) => res((reader.result as string))
    })
```
* Constructing a file from the provided blob, and returning the data
** similar to the above example

How am I meant to transform the blob data so as to allow the request to provide what's required. I'm attempting to build a simple Angular service to allow me to talk to Whisper ASR directly, without a backend running.

The full service file looks like this:
```
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Observable, from, switchMap } from 'rxjs';
@Injectable({
  providedIn: 'root'
})
export class WhisperService {

  private readonly apiUrl = 'http://localhost:9000'
  constructor(private http: HttpClient) { }

  recognize(data: Blob): Observable<any> {
    return from(this._blobToBinary(data)).pipe(
      switchMap((audioFile: string) => {
        console.log(audioFile)
        const headers: HttpHeaders = new  HttpHeaders();
        headers.set('Content-Type', 'multipart/form-data');
        const body: HttpParams = new HttpParams({
          fromObject: {
            audio_file: audioFile
          }
        });
        return this.http.post(`${this.apiUrl}/asr`, body, { headers })
      })
    )
  }

  private async _blobToBinary(data: Blob): Promise<string> {
    return new Promise((res, rej) => {
      const reader = new FileReader();
      reader.readAsDataURL(data)
      reader.onloadend = (event) => res((reader.result as string).split('base64,')[1])
    })
  }

}
```

**Comment by moz-gh** [comment]
I had trouble with the same thing - couldn't get a proper response back from the Whisper API. I monitored the network request made by the "Try it out" feature on the swagger docs - first I tried copying the POST request via Firefox devtool's network tab but it didn't work. Instead, I copied the curl request it provides and used a tool like https://www.kodytools.com/curl-converter to convert it with the correct file format/headers and it worked! 

Here is a JS example w/ fetch that worked for me (in a browser environment):
```javascript
const blob = <blob data>;
const form = new FormData();
form.append(
    "audio_file",
    File(["blob"], "${filenameWithExtension};type=audio/x-wav")
);

fetch(
    "http://localhost:9000/asr?task=transcribe&language=en&encode=true&output=json",
    {
        method: "POST",
        headers: {
            accept: "application/json",
            "Content-Type": "multipart/form-data",
        },
        body: form,
    }
);
```

Hope that helps!
