### ISSUE TITLE
unraid docker GPU not working.

### ISSUE THREAD

**Issue by brainbudt** [ahmetoner/whisper-asr-webservice#107]
Hello,

I can't seem to get the GPU to be working in a docker for Unraid. Like the information said I have added the "--gpus all" in “Extra arguments”, but when I give it a try it will just use the CPU and not GPU.

**Comment by qjao** [comment]
Try adding"--runtime nvidia" to extra parameters as well. 
And a Container Variable with the followings: 
Key: NVIDIA_VISIBLE_DEVICES
Value: all

**Comment by jim608** [comment]
I have the same issue with Unraid’s Docker. When I enter the nvidia-smi command in the Docker terminal, it can correctly identify the GPU, but Whisper still uses the CPU to work. I tried adding “–runtime nvidia” to the extra parameters and a Container Variable with Key: NVIDIA_VISIBLE_DEVICES and Value: all, but it still doesn’t work with the GPU.

**Comment by JoaoPedroBelo** [comment]
I solved the issued by downloading the docker GPU version.

onerahmet/openai-whisper-asr-webservice:latest-gpu

**Comment by BloodshedRomance** [comment]
On Unraid 6.12.2 after the docker is created you can go in and modify it. In the top right there is a toggle for advanced options and I just removed the --gpus all option and let it run on CPU only and it worked fine. Documentation on the Unraid side was pretty vague on how to do this from what I was able to gather.

![Screenshot 2023-08-28 210508](https://github.com/ahmetoner/whisper-asr-webservice/assets/69774822/ae7bf2c8-80ab-427d-8044-3a3497a2d728)

**Comment by YMan84** [comment]
> I solved the issued by downloading the docker GPU version.
> 
> onerahmet/openai-whisper-asr-webservice:latest-gpu

This solved the issue for me as well with a GTX 1070 and the Nvidia Driver plugin installed. Did not need to add the extra parameters or variables, just had to pull the `latest-gpu` version

**Comment by kmxverick** [comment]
> I solved the issued by downloading the docker GPU version.
> 
> onerahmet/openai-whisper-asr-webservice:latest-gpu

Thank you for your recommendation. Using that, plus the extra parameters and a system reboot seems to have done the trick for me.
