### ISSUE TITLE
Inquiring about the default value of the output query param as TXT instead of JSON

### ISSUE THREAD

**Issue by mushifali** [ahmetoner/whisper-asr-webservice#116]
We recently performed an upgrade to the latest version, which resulted in a disruption. Upon investigation, we discovered that the default response format is no longer JSON as it used to be a few months ago. Upon reviewing the code, we observed that the default value for the `output` query parameter is set to `txt`, instead of `json`.

We have made the necessary adjustments on our end to accommodate this change. However, we would appreciate clarification regarding the reasoning behind this modification. Considering that JSON is typically the expected response format for REST APIs, we are curious to understand the rationale behind the shift to TXT.

**Comment by ayancey** [comment]
The default was json until [this commit](https://github.com/ahmetoner/whisper-asr-webservice/commit/321a00c148627aa576ddb3774f20c2b1869815e4) in February. We will look into changing the defaults, but for now please specify the output format you would like. Thank you.
