### ISSUE TITLE
CORS Policy Issues

### ISSUE THREAD

**Issue by asktimfisher** [ahmetoner/whisper-asr-webservice#119]
I'm working completely locally and am utilizing the API via JS. Very simple stuff. However, I'm getting a CORS policy issues when I hit the local API. Thoughts?

**Comment by ayancey** [comment]
You could pass the API through nginx and add the CORS headers. A feature to enable CORS would be nice though, maybe an environment variable toggle?

**Comment by asktimfisher** [comment]
Yes! That would be fantastic. I ended up circumventing with a Chrome add-on but you're right - adding via nginx would be best. Or best yet: your suggestion!

**Comment by etochavez** [comment]
Hello, I have the same issue. It works if I run it locally but when I try to use it from another pc with the ip adders it doesn't work. What can I do to solve this issue?

**Comment by ayancey** [comment]
> Hello, I have the same issue. It works if I run it locally but when I try to use it from another pc with the ip adders it doesn't work. What can I do to solve this issue?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by dahifi** [comment]
Just an FYI for anyone else stuck in CORS hell, you can set the allowed hosts by adding the following to webservice.py:

```
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    # Existing block of code w options
)

allowed_origins = [
    "http://localhost:5173",  # Make sure this matches the port your frontend is running on
    "https://yourfrontenddomain.com",  # Replace this with your actual frontend domain
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,  # List of allowed origins
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)
```
I think it would be a nice feature to have a way to inject the allowed origins into an env var for runtime.
