### ISSUE TITLE
Add confidence percentage to language detection

### ISSUE THREAD

**Issue by darrenwinslow** [ahmetoner/whisper-asr-webservice#120]
Would it be possible to add a confidence score to the language detection?

**Comment by gleithoernchen** [comment]
Hi,
I was wondering why these confidence scores are such strange numbers? I works fine in detecting the language correctly but the confidence score is like:
3.592407438191003e-06
1.951540252775885e-05
1.8163596905651502e-05
I expected something like_: 0.854, 1.0, 0.54 or similiar. Can anyone explain me how to interpret these numbers?
Thanks
