### ISSUE TITLE
FP16 is not supported on CPU; using FP32 instead

### ISSUE THREAD

**Issue by Temoxa** [ahmetoner/whisper-asr-webservice#121]
Hello, iam use MacOs M1, and run command by your instructions

`docker run -d -p 9000:9000 -e ASR_MODEL=base -e ASR_ENGINE=openai_whisper onerahmet/openai-whisper-asr-webservice:latest`

and get some error

<img width="1029" alt="image" src="https://github.com/ahmetoner/whisper-asr-webservice/assets/21303126/4e500543-1d92-4b60-b1f7-ba2d332a2f72">

**Comment by ayancey** [comment]
That’s a warning. I think it means you will be using CPU instead of GPU or whatever neural cores the M1 has. 

Don’t think M1 is supported for that yet https://github.com/openai/whisper/discussions/51

**Comment by Temoxa** [comment]
thanks, in docker i can change model, that recognizing will be faster ?

**Comment by ayancey** [comment]
base is the smallest and fastest model.

**Comment by Temoxa** [comment]
when i call this method 

<img width="1386" alt="image" src="https://github.com/ahmetoner/whisper-asr-webservice/assets/21303126/d4879974-28b2-436d-b97f-f82f71f1d5c1">

He use "base" model?

**Comment by ayancey** [comment]
The model is chosen by the environment variable you set in the docker run command.
