### ISSUE TITLE
docker can't pull docker.io/onerahmet/openai-whisper-asr-webservice:latest

### ISSUE THREAD

**Issue by SYD-Fish** [ahmetoner/whisper-asr-webservice#124]
(base) [jmsadmin@yc-nsg-c84 ~]$ sudo docker search whisper-asr-webservice
INDEX       NAME                                                DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
docker.io   docker.io/onerahmet/openai-whisper-asr-webservice   https://github.com/ahmetoner/whisper-asr-w...   29
docker.io   docker.io/pererinha/whisper-asr-webservice                                                          0
docker.io   docker.io/tpsdata/openai-whisper-asr-webservice     Fork of https://github.com/ahmetoner/whisp...   0
docker.io   docker.io/wavelengthapp/whisper-asr-webservice                                                      0
(base) [jmsadmin@yc-nsg-c84 ~]$ sudo docker pull docker.io/onerahmet/openai-whisper-asr-webservice
Using default tag: latest
Trying to pull repository docker.io/onerahmet/openai-whisper-asr-webservice ...
manifest for docker.io/onerahmet/openai-whisper-asr-webservice:latest not found

**Comment by ayancey** [comment]
Can you try this again and let me know if it works? I'm unable to replicate this.
