### ISSUE TITLE
[Question] Inconsistency in Model Weight Precision during Conversion and Initialization

### ISSUE THREAD

**Issue by EvilFreelancer** [ahmetoner/whisper-asr-webservice#127]
Hello,

I am currently writing an article about your project, and while examining the source code of the `faster_whisper` engine, I've noticed an intriguing detail in the [`model_converter` function](https://github.com/ahmetoner/whisper-asr-webservice/blob/main/app/faster_whisper/utils.py#L10) as well as during the initialization stage of the [`WhisperModel`](https://github.com/ahmetoner/whisper-asr-webservice/blob/main/app/faster_whisper/core.py#L17).

In brief, the model conversion is carried out to a precision of `float16`. However, the model is initialized in `float32` mode. If both the conversion and initialization were done with the same weight precision, the VRAM memory usage would decrease by as much as half.

Could you please provide some insight into the reason behind this discrepancy?

Thank you for your time and consideration.

**Comment by ayancey** [comment]
Apologies for the slow response on this issue and your PR. Will have time this week for this.

**Comment by ayancey** [comment]
Closed with release of v1.2.
