### ISSUE TITLE
Upgrade to openai whisper v20230918

### ISSUE THREAD

**Issue by ankurkgupta** [ahmetoner/whisper-asr-webservice#131]
It is important to update openai whisper version from [openai/whisper](https://github.com/openai/whisper)@[v20230124](https://github.com/openai/whisper/releases/tag/v20230124) to [openai/whisper](https://github.com/openai/whisper)@[v20230918](https://github.com/openai/whisper/releases/tag/v20230918) as the quality of the generated transcript is better with newer version

**Comment by ayancey** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by DuzAwe** [comment]
@ayancey Do I simply update the version in the pyproject.toml file or do I need to do more? I can find no core.py in the whisper project.

**Comment by ayancey** [comment]
I think you need to update the pyproject.toml file and then run poetry update to lock the dependencies.

**Comment by ahmetoner** [comment]
Hello, we will have a new release this weekend with [openai/whisper](https://github.com/openai/whisper)@[v20230918](https://github.com/openai/whisper/releases/tag/v20230918) and [faster-whisper](https://github.com/guillaumekln/faster-whisper)@[0.9.0](https://github.com/guillaumekln/faster-whisper/releases/tag/v0.9.0)

**Comment by ahmetoner** [comment]
see [v1.2.0](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.2.0)
