### ISSUE TITLE
Ballpark resources needed to get relatively speedy results?

### ISSUE THREAD

**Issue by banagale** [ahmetoner/whisper-asr-webservice#135]
This is a bit handwavey, but can anyone give feedback on what kind of system resources are needed to generate solid TTS processing from this?

I understand a new release is coming with an updated version of whisper that might change performance.

I am running the current version CPU only on an MBA M2 and am pretty happy with the speed. 

I'm curious how people are deploying `whisper-asr-webservice` apart from local dev, and under what configurations.

**Comment by ayancey** [comment]
Your Macbook Air M2 is definitely capable of running whisper and producing solid results, but you need to choose a backend and pick a model size that balances speed with accuracy.

This project supports two backends right now, [whisper](https://github.com/openai/whisper), and [faster-whisper](https://github.com/guillaumekln/faster-whisper). The original whisper doesn't run very well on CPUs. faster-whisper is, faster.

However, there is [whisper.cpp](https://github.com/ggerganov/whisper.cpp), which we don't yet support, but judging from [this benchmark ](https://github.com/guillaumekln/faster-whisper/discussions/368#discussioncomment-6507263) can run even faster on your device.

**Comment by banagale** [comment]
Thanks for that. I am curious about remote hosting, though. 
The goal would be to run this as a service to another product I have running on the web.  Have you experimented with different configs on cloud based persistent service with GPUs?

Or perhaps an efficient way to use this in an on demand, transient resource?

**Comment by ayancey** [comment]
> Thanks for that. I am curious about remote hosting, though. The goal would be to run this as a service to another product I have running on the web. Have you experimented with different configs on cloud based persistent service with GPUs?
> 
> Or perhaps an efficient way to use this in an on demand, transient resource?

You haven't specified what your time requirements are. You can run any model you want on most CPUs/GPUs as long as you have the RAM/VRAM, but the speed will vary greatly.

**Comment by banagale** [comment]
You're right and I do not have my own benchmark for what is fast enough.  I am working on service implementation now, so I may be able to give some feedback here when I've tried it on various common VPS resources.

**Comment by ayancey** [comment]
> You're right and I do not have my own benchmark for what is fast enough. I am working on service implementation now, so I may be able to give some feedback here when I've tried it on various common VPS resources.

Please let us know!

**Comment by banagale** [comment]
Took me a minute but I have a working setup of vps standup and basic config using terraform and github actions for CI build and deployment of this service.

I'm working on a draft of the blog entry about this [here](https://chiefofstaffhq.com/blog/resource-requirements-for-a-whisper-stt-web-service/), and will try to get it better styled and provide actual benchmarks as I make more progress. 

But I thought I'd share what I saw when it failed at least.

My setup uses `nginx-proxy` and `jrcs/letsencrypt-nginx-proxy-companion` in front of the gunicorn web instance in this repo.

### Not Enough Resources 
So far, I have tested it on Digital Ocean's smallest droplet, "Regular Intel" with a 1vCPU, 1 GB memory ($6/mo) and found this was not enough to complete a short transcription.  

Here's a quick pass at diagnostics for this service failing due to insufficient resources.

After the normal warning about FP16/FP32 I had the following logs:

```
/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
**[2023-10-11 05:17:18 +0000] [1] [WARNING] Worker with pid 25 was terminated due to signal 9**
[2023-10-11 05:17:19 +0000] [27] [INFO] Booting worker with pid: 27
[2023-10-11 05:17:23 +0000] [27] [INFO] Started server process [27]
[2023-10-11 05:17:23 +0000] [27] [INFO] Waiting for application startup.
[2023-10-11 05:17:23 +0000] [27] [INFO] Application startup complete.
```

You can see more details using `dmesg` on the host, which included the log:

```
[47344.013944] Out of memory: Killed process 36117 (gunicorn) total-vm:1334116kB, anon-rss:621308kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:2120kB oom_score_adj:0
```

### Enough Resources

This is probably the key question what is enough?

Once I had server up and working, I cranked up the resources and found "Premium Intel", 2 vCPUs, 2 GB RAM ($21/mo) to handle inbound STT requests no problem. 

Key to this is, well how fast was it and under what config, and again I haven't measured yet, but at least it runs the model at a speed that can service another app.

I'm going to spec the testing audio file and configuration (whisper / faster-whisper) to do benchmarking. If anyone has a recommendation on one or more audio files for benchmarking STT services I'd take em.

I'll try to come back and bump this issue when I make more progress on this question.

**Comment by ayancey** [comment]
You're going to have a tough time without a GPU. Try whispercpp if you can't get an instance with a GPU.
