### ISSUE TITLE
Invalid path for `cache-whisper` volume under macOS in docker-compose.

### ISSUE THREAD

**Issue by banagale** [ahmetoner/whisper-asr-webservice#138]
[This line](https://github.com/ahmetoner/whisper-asr-webservice/blob/8db9450c4d16b4c808d5f06f73310f09eb3e3af6/docker-compose.yml#L16) of `docker-compose.yml`:

```
      - cache-whisper:~/.cache/whisper
```

Seems to be valid under linux, but fails as invalid under macOS:

```
Error response from daemon: invalid mount config for type "volume": invalid mount path: '~/.cache/whisper' mount path must be absolute
```

I changed it out for:

```
      - cache-whisper:${HOME}/.cache/whisper
```

I haven't tested it on linux, but this syntax [supposedly covers](https://stackoverflow.com/a/62408283/4028977) mac and linux in docker 3+.

Handling various windows docker-compose run methods seems to require [additional muckery](https://stackoverflow.com/a/72495783/4028977), and I don't have a way to test that so leaving it out.

If you agree with this change / want it in, lmk and I'd be happy to provide a PR for this one liner.

**Comment by ayancey** [comment]
It would be nice to implement a fix if we could, but I'm not sure I understand. Are you talking about Docker Desktop? Since that uses a Linux VM I don't really know how running docker-compose directly on the mac to control the underlying VM works.

**Comment by ahmetoner** [comment]
Hey @banagale, can you try following path? 

```yaml
      - cache-whisper:/root/.cache/whisper
```
