### ISSUE TITLE
Does amdgpu support it?

### ISSUE THREAD

**Issue by taikai-zz** [ahmetoner/whisper-asr-webservice#141]
Does amdgpu support it?

**Comment by ayancey** [comment]
Hi,

I think rocm does work with whisper. Please see this thread: https://github.com/openai/whisper/discussions/55

You will need to clone our repo and modify the dockerfile or poetry file. Please let us know how it works out!

**Comment by ayancey** [comment]
We might have hardcoded references to CUDA. If you can explore how well AMD works for acceleration that would help a lot.
