### ISSUE TITLE
Diarization support

### ISSUE THREAD

**Issue by dahifi** [ahmetoner/whisper-asr-webservice#142]
So I wanted to see if there was any desire to add diarization features to this repo? 

I was able to get https://github.com/MahmoudAshraf97/whisper-diarization running on my GPU and would like to make it available to the same Obsidian plugin workflow that I'm using for my day to day. I haven't started any work modifying this repo yet, as I'm running this in a docker container and am not 100% on how to stand up a dev setup yet.

**Comment by ayancey** [comment]
We have a PR right now that integrates WhisperX. Does this differ from that?

**Comment by dahifi** [comment]
AHA! I didn't realize that's what it was. I'll take a look at that and see if I can get it working.
