### ISSUE TITLE
Issue with Processing Large Files (80MB)

### ISSUE THREAD

**Issue by blockfer-rp** [ahmetoner/whisper-asr-webservice#143]
Hello,

I'm running this project on Google Cloud Run. When I process files that are between 30MB to 40MB, everything works fine. However, when I try to process a file that is around 80MB, I encounter a "413 Request Entity Too Large" error.

I'm not sure where this error is coming from. Is there a way to control the file size limits within the code, or is there a feature to automatically split larger files into smaller chunks for processing?

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>413 Request Entity Too Large</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Request Entity Too Large</h1>
<h2>Your client issued a request that was too large.
</h2>
<h2><script>
  (function() { var c=function(a,d,b){a=a+"=deleted; path="+d;null!=b&&(a+="; domain="+b);document.cookie=a+"; expires=Thu, 01 Jan 1970 00:00:00 GMT"};var g=function(a){var d=e,b=location.hostname;c(d,a,null);c(d,a,b);for(var f=0;;){f=b.indexOf(".",f+1);if(0>f)break;c(d,a,b.substring(f+1))}};var h;if(4E3<unescape(encodeURI(document.cookie)).length){for(var k=document.cookie.split(";"),l=[],m=0;m<k.length;m++){var n=k[m].match(/^\s*([^=]+)/);n&&l.push(n[1])}for(var p=0;p<l.length;p++){var e=l[p];g("/");for(var q=location.pathname,r=0;;){r=q.indexOf("/",r+1);if(0>r)break;var t=q.substring(0,r);g(t);g(t+"/")}"/"!=q.charAt(q.length-1)&&(g(q),g(q+"/"))}h=!0}else h=!1;
h&&setTimeout(function(){if(history.replaceState){var a=location.href;history.replaceState(null,"","/");location.replace(a)}},1E3); })();

</script>
</h2>
</body></html>

**Comment by ayancey** [comment]
>As per official GCP documentation, the maximum request size limit for Cloud Run (which is 32 MB) cannot be increased. No limit if using HTTP/2 server.

https://cloud.google.com/run/quotas#cloud_run_limits
