### ISSUE TITLE
I need you to provide detailed information about the API

### ISSUE THREAD

**Issue by musellama** [ahmetoner/whisper-asr-webservice#145]
import requests

url = "http://localhost:9000/asr?task=transcribe&encode=true&output=txt&word_timestamps=false"

payload={}
files=[
   ('audio_file',('D:\hello.wav',open('D:\\hello.wav','rb'),'audio/wav'))
]
headers = {
   'Accept': 'application/json',
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
   'Content-Type': 'multipart/form-data',
   'Host': 'localhost:9000',
   'Connection': 'keep-alive'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)

out print
{"detail":"Missing boundary in multipart."}

There is no problem with this code, right? But why is an error returned 
Can anyone provide a detailed example of the correct format

**Comment by musellama** [comment]
help me

**Comment by ayancey** [comment]
The asr endpoint uses POST, not GET. Please refer to the swagger docs.
