### ISSUE TITLE
Add VAD feature for faster-whisper

### ISSUE THREAD

**Issue by dev-jesser** [ahmetoner/whisper-asr-webservice#147]
In `faster-whisper` there's a built-in VAD feature. It's set to default to `false` [here](https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/transcribe.py#L195-L196C66)

This feature should be helpful to handle instances which I believe are called "hallucinations" - the speaker goes silent for some time, then picks up again, but the resulting text is just repeating the last sentence before the person went silent.

Can a parameter be added to the REST API to optionally set this `vad_filter` feature to `true` and add `vad_parameters`?

**Comment by blundercode** [comment]
I also agree this feature would be useful, VAD seems to be the standard now for whisper and would love to see it used here.
