### ISSUE TITLE
GPL2.0 dependency

### ISSUE THREAD

**Issue by ostpachukAndrii** [ahmetoner/whisper-asr-webservice#149]
Hi guys, hope you are doing great. 
Got a quick question about your product's licensing. Noticed your dependency on unidecode@1.3.6 rolling with GPL 2.0. That means anyone who integrate with your product need to splash the whole product into public. Do you plan to get rid of this library or do you plan stick to GPL2.0.

**Comment by ayancey** [comment]
I wonder which shadowy company you represent? In all seriousness, this is a good question. It seems that we cannot be MIT licensed as long as we are using GPL licensed code.
