### ISSUE TITLE
Swagger version mismatch

### ISSUE THREAD

**Issue by neon-ninja** [ahmetoner/whisper-asr-webservice#154]
When visiting /docs, I get this error:

```
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```
Indeed, the version in /openapi.json is ` "openapi": "3.1.0",`

**Comment by paultepe** [comment]
I get the same error.

**Comment by RainbowXie** [comment]
the same.

**Comment by neon-ninja** [comment]
oh, this is a duplicate of https://github.com/ahmetoner/whisper-asr-webservice/issues/153. You beat me by one minute @paultepe ;)

**Comment by hulleyrob** [comment]
ive just spent an hour trying to fix this error and it went away by putting the docs folder inside /app.
