### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by RainbowXie** [ahmetoner/whisper-asr-webservice#159]
I'm using Unraid, and updated to the latest version, but still get the same error:

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/34147843/2bd79246-1bec-412c-985d-3bff7dac4025)

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/34147843/7f46acec-4652-4f32-a706-6f227a6d4482)

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/34147843/efc6088a-b577-4b23-8116-96023ceaf200)

**Comment by ahmetoner** [comment]
Could it be browser caching? Have you tried CTRL + SHIFT + R?

**Comment by RainbowXie** [comment]
> Could it be browser caching? Have you tried CTRL + SHIFT + R?

Oh yes, I forgot it. thx~
