### ISSUE TITLE
Whisper-Large-V3 Support

### ISSUE THREAD

**Issue by blundercode** [ahmetoner/whisper-asr-webservice#161]
https://github.com/openai/whisper

Whisper-Large-v3 dropped today, any chance we could get support, very excited to test this out!

I am praying this cuts down hallucinations.

Thanks for the repo love it!

**Comment by ahmetoner** [comment]
please see https://github.com/ahmetoner/whisper-asr-webservice/pull/160

**Comment by blundercode** [comment]
> please see #160

Wow so fast! Our hero! 

Have you played around with it are you impressed?

**Comment by ahmetoner** [comment]
New release [v1.2.3](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.2.3) is out for [openai/whisper](https://github.com/openai/whisper)@[v20231106](https://github.com/openai/whisper/releases/tag/v20231106). 

Also, I was attempting to publish the `faster-whisper` model converter as well, but it appears that the `feature_size` has changed from `80` to `128` for the `large-v3` model ([source](https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/feature_extractor.py#L8)). Let's wait for @guillaumekln to update it first, and then we can proceed with the new release for `faster-whisper`.

@blundercode I didn't find time to play around, please share your first impressions when you have it.

**Comment by WeberJulian** [comment]
Hey @ahmetoner, faster-whisper@0.10.0 just dropped with large-v3 support. Would it be possible for you to update this repo please?

**Comment by ahmetoner** [comment]
They haven't released a new version on PyPI yet. I will update the repository whenever they publish on PyPI. 
Please refer to https://github.com/SYSTRAN/faster-whisper/issues/581 for more information.

**Comment by ahmetoner** [comment]
Please see [v1.2.4](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.2.4)
