### ISSUE TITLE
Recommended Hardware requirements

### ISSUE THREAD

**Issue by ostpachukAndrii** [ahmetoner/whisper-asr-webservice#164]
Hello team,
Could you kindly share the recommended hardware requirements for whisper-asr-webservice?

As of now, the only hardware limitation I've identified is the need for an NVIDIA card with CUDA support. Do you have some other CPU, GPU, or RAM limitations or some suggestions related to hardware?

**Comment by ayancey** [comment]
You don't need a GPU to use whisper, but it helps a lot.

**Comment by ayancey** [comment]
Please refer to the requirements and benchmarks on the repos for each backend:

https://github.com/openai/whisper#available-models-and-languages

https://github.com/SYSTRAN/faster-whisper#benchmark
