### ISSUE TITLE
Failed To Fetch

### ISSUE THREAD

**Issue by Jessomadic** [ahmetoner/whisper-asr-webservice#165]
I set up the webservice in Docker after much struggling and went to test it out but it seems to be failing when I upload files as a test.
The error says its possibly a memory issue but my GPU (3070) has 8gb and hardly uses over 1 when running this in Docker. Am I doing something wrong or is this a bug

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/35648348/dd936d41-bff0-4886-9884-a967db1f71f8)

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/35648348/cb3cf09f-77fe-4fda-b03b-277c74c3a669)

**Comment by teran1983** [comment]
Using a symbolic server name instead of an IP helped me.
for example: http://server:9000 instead http://192.168.0.5:9000

**Comment by Jessomadic** [comment]
> Using a symbolic server name instead of an IP helped me. for example: http://server:9000 instead http://192.168.0.5:9000 but I use CPU decoding and having 20GB RAM

I have it set up in Docker like this. Not sure how I would change it to a Symbolic name. I feel like such a newbie lol
![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/35648348/d8eaeca1-330b-42aa-94c6-b5995eda50fa)

**Comment by Jessomadic** [comment]
Well I figured out what that error was. Way Way back I limited Docker to 1GB of system memory because there was a memory leak and that helped prevent it. So it was erroring out with that "Out of Memory" error not because of a lack of Vram but a lack of allowed System Memory
