### ISSUE TITLE
Error loading heavy models

### ISSUE THREAD

**Issue by anastasia-tskhay** [ahmetoner/whisper-asr-webservice#166]
I can't load models v2 and v3. The container freezes and nothing happens.

**Comment by anastasia-tskhay** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 2.30 GiB already allocated; 51.56 MiB free; 2.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF  - also gives the same error. How much video memory do you need?

**Comment by ayancey** [comment]
How much VRAM does your GPU have? Sounds like it's not enough to run the model.
