### ISSUE TITLE
Use all Cores full?

### ISSUE THREAD

**Issue by wuast94** [ahmetoner/whisper-asr-webservice#167]
I tadded ENV OMP_NUM_THREADS=44 to the container so faster whisper could use more cores, it works i think but not utilizing all cores full. when using 4 threats all threats are at 100%, using all 48 threats it looks like this:

![image](https://github.com/ahmetoner/whisper-asr-webservice/assets/16965460/e1ae01e8-c766-4fd3-b549-57aa60259903)

i would say i have more than enaugh processing power left to use

**Comment by ayancey** [comment]
Does the same thing occur if you try to use faster-whisper directly? (https://github.com/SYSTRAN/faster-whisper)

I'm not sure this is a problem with the ASR project.

**Comment by wuast94** [comment]
ok its a problem from faster-whisper
