### ISSUE TITLE
Did not find boundary character 91 at index 2

### ISSUE THREAD

**Issue by asktimfisher** [ahmetoner/whisper-asr-webservice#174]
I'm using NodeJS and when I send an audio buffer through I get the following error in the docker container log: "Did not find boundary character 91 at index 2". I know this isn't technically an issue on your end as I can save a file from my code and POST it manually via Postman and I get a clean/fast transcription. That said - I was wondering if that message meant anything to you (or anyone reading) that might send me in the right direction. Thanks!

**Comment by ayancey** [comment]
Post code

**Comment by asktimfisher** [comment]
I'm using NodeJS and the form-data package to send a WAV buffer to the ASR endpoint. I know the audio coming into the function is good because I can use it via Postman with the Whisper endpoint and it works great.

`
async function` transcribeAudio(socket, audioBuffer) {
  const formData = new FormData();
  formData.append("audio_file", audioBuffer, {
    contentType: "audio/wav",
    filename: "audio.wav",
  });

  const whisperUrl =
    "http://192.168.0.10:9000/asr?task=transcribe&language=en&encode=true&output=json&word_timestamps=false";

  try {
    const response = await fetch(whisperUrl, {
      method: "POST",
      body: formData,
      headers: formData.getHeaders(),
    });

    if (!response.ok) {
      socket.emit(
        "clientConsole",
        `Whisper HTTP error! Status: ${response.status}`
      );
    }

    const data = await response.json();
    const transcription = data.text;

    console.log("Transcribed text:", transcription);
    socket.emit("clientConsole", `Transcribed text: ${transcription}`);
  } catch (error) {
    console.error("Error during Whisper transcription: ", error);
    return null;
  }
}
`

But I get "undefined" returned and a "Did not find boundary character 91 at index 2" in the logs.

This is the first time I'm POSTing with form data in Node so I certainly could be crafting something wrong.

**Comment by ahmetoner** [comment]
Have you tried using Postman [code snippets](https://learning.postman.com/docs/sending-requests/generate-code-snippets/) for making Node.js requests?

**Comment by asktimfisher** [comment]
No!! I didn't know that was an option! That's a great idea. I'll try that when I get home. At very least, even if that fails, it should make it clear if perhaps I'm missing a step (since I'm using a legit file in Postman vs a buffer (same audio data) in the code). Thanks for the idea!

**Comment by asktimfisher** [comment]
Thanks so much for the recommendation! I was able to create the following NodeJS code that accepts a WAV buffer. Works perfectly. I think switching to axios from the native fetch did the trick:

`async function transcribeAudio(buffer) {
  let data = new FormData();
  // Append the buffer directly, instead of reading from a file
  // The second argument ('file.wav') is the filename that will be sent with the form data
  data.append('audio_file', buffer, 'file.wav');

  let config = {
    method: 'post',
    maxBodyLength: Infinity,
    url: 'http://192.168.0.10:9000/asr?task=transcribe&language=en&encode=true&output=json&word_timestamps=false',
    headers: {
      ...data.getHeaders(),
    },
    data: data,
  };

  try {
    const response = await axios.request(config);
    console.log(JSON.stringify(response.data));
  } catch (error) {
    console.log(error);
  }
}`
