### ISSUE TITLE
[!Important] GPL2.0 issue - ffmpeg

### ISSUE THREAD

**Issue by ostpachukAndrii** [ahmetoner/whisper-asr-webservice#193]
Hi team, 
please fix the license violation issue ASAP. 

If a service uses FFmpeg with the --enable-gpl configuration, it cannot be licensed under a permissive license like the MIT license. This is because the GPL license, under which FFmpeg is distributed with this configuration, requires that any derivative works be distributed under the same terms. Therefore, incorporating FFmpeg with --enable-gpl into a service would typically mean that the service must also be licensed under the GPL or a compatible license, which is not possible with the MIT license. This creates a licensing conflict, as the requirements of the GPL are more restrictive than those of the MIT license. To avoid legal issues and ensure compliance, developers should choose a compatible license for their service if they intend to use FFmpeg with the --enable-gpl configuration.

https://www.ffmpeg.org/legal.html

**Comment by ayancey** [comment]
@ahmetoner Do we know which audio codecs may be affected by this? I think it would likely be okay to disable gpl features and test it out.

**Comment by ahmetoner** [comment]
Thank you for reporting, @ostpachukAndrii. We will be releasing an update soon after we're done with MR #194. 
However, please note that the audio file conversions in the updated version might be slightly slower due to private compiling without GPL libs.

@ayancey, here is an example of our FFmpeg code:

```bash
ffmpeg -i input.wav -ac 1 -ar 16000 -acodec pcm_s16le output.wav
```
