### ISSUE TITLE
[Important] HTTP Request Smuggling

### ISSUE THREAD

**Issue by ostpachukAndrii** [ahmetoner/whisper-asr-webservice#217]
Dear Whisper-ASR-Webservice Team,

I hope this message finds you well.

I regret to inform you that a critical security vulnerability has been identified in one of service dependencies, specifically **gunicorn** version **21.2.0**. It is imperative that we **upgrade to version 22.0.0** immediately to address this issue.

The vulnerability in question pertains to HTTP Request Smuggling, resulting from improper validation of Transfer-Encoding headers within affected versions. This flaw could potentially enable attackers to circumvent security measures and gain unauthorized access to restricted endpoints by crafting requests with conflicting Transfer-Encoding headers.

Given the severity of this issue, I urge everyone to prioritize the update process without delay.

Thank you for your swift attent!

**Comment by ayancey** [comment]
Thank you for your report. This was fixed by #231.
