### ISSUE TITLE
How to set 'language parameter'

### ISSUE THREAD

**Issue by zodac** [ahmetoner/whisper-asr-webservice#225]
When I start up the service in docker, I see the following log entry on start-up:
`The current model is English-only but the language parameter is set to 'ja'; using 'en' instead.`

Is there an environment variable to set to configure this?

Currently the only environment variables I pass in are the following two:

```
    environment:
      ASR_MODEL: "small.en"
      ASR_ENGINE: "faster_whisper"
```

**Comment by e950280** [comment]
Because the model you are using is small.en, and it only has the ability to translate English, but you set the language to ja.

BTW, XXX.en means it only handles English.

**Comment by zodac** [comment]
Ahh, I see, that was silly of me. It's an issue with the file, not the service itself. Ok, that makes sense. Thanks for pointing that out. :)
