### ISSUE TITLE
Deploying from Source Code When Docker is Unavailable on the Server

### ISSUE THREAD

**Issue by thb10086** [ahmetoner/whisper-asr-webservice#232]
How can I deploy using the source code if Docker is not available on the server?

**Comment by xiangxiang-meifannao** [comment]
Look this https://ahmetoner.com/whisper-asr-webservice/build/#poetry

**Comment by thb10086** [comment]
> 看看这个 https://ahmetoner.com/whisper-asr-webservice/build/#poetry

我使用这个部署. 使用的是CPU而不是GPU

**Comment by thb10086** [comment]
@xiangxiang-meifannao hi help me

**Comment by ayancey** [comment]
https://python-poetry.org/docs/
