### ISSUE TITLE
Translation Function Not Working - Outputs Always in English

### ISSUE THREAD

**Issue by ceti-byte** [ahmetoner/whisper-asr-webservice#240]
Hello,

I am encountering an issue with the translation function of Whisper on my home server. The transcription feature works perfectly, but when I try to use the translation function, the request is not processed correctly. Here are my setup details:

- Server: Unraid  
- Docker Image: Whisper as a Web Service (latest version)

I followed the installation instructions carefully, and other functions seem to work without any problems. However, the translation of audio files fails without specific error messages. Everything is always output in English instead of German.

Could you please provide guidance on how to resolve this issue, or if there are any additional configurations required to make the translation work on this system?

Thank you for your help and for developing this tool!

Best regards,  
Oliver

**Comment by ayancey** [comment]
Whisper can only translate into English.
