### ISSUE TITLE
Dockerfile.gpu does not build, errors out installing torch

### ISSUE THREAD

**Issue by tariqislam** [ahmetoner/whisper-asr-webservice#249]
Running on a Macbook M1 -- does that matter?

Prior to this error, when setting up the build env when I run:

`pip3 install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch`

I get:

```
Looking in links: https://download.pytorch.org/whl/torch
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==1.13.1+cu117
```

Similarly, when running docker build for the GPU, the following error is obtained:

```
 => ERROR [stage-2 15/15] RUN /app/.venv/bin/pip install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch                                                                      1.1s
------
 > [stage-2 15/15] RUN /app/.venv/bin/pip install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch:
0.306 Looking in links: https://download.pytorch.org/whl/torch
0.994 ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
1.044 ERROR: No matching distribution found for torch==1.13.1+cu117
------

 1 warning found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 84)
Dockerfile.gpu:80
--------------------
  78 |
  79 |     RUN poetry install
  80 | >>> RUN $POETRY_VENV/bin/pip install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch
  81 |
  82 |     EXPOSE 9000
--------------------
ERROR: failed to solve: process "/bin/sh -c $POETRY_VENV/bin/pip install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch" did not complete successfully: exit code: 1
```

**Comment by ayancey** [comment]
> Running on a Macbook M1 -- does that matter?

Yep. You're trying to install pytorch with nvidia CUDA drivers, which are only supported on nvidia gpus. The gpu docker tag only supports CUDA.

If you are using docker desktop on macos, you are really just using a Linux VM. If you want to use Apple Silicon acceleration (Metal Performance Shaders), you have to run whisper natively.

You're better off trying https://github.com/ggerganov/whisper.cpp, which has good support for Apple Silicon.

**Comment by tariqislam** [comment]
@ayancey I see. In fact, what I'm trying to do is build the docker image on my Mac, but use it on AMD64 in Ubuntu. I guess I have to do the docker build on an Ubuntu AMD64 machine as well, is that correct?

**Comment by ayancey** [comment]
> @ayancey I see. In fact, what I'm trying to do is build the docker image on my Mac, but use it on AMD64 in Ubuntu. I guess I have to do the docker build on an Ubuntu AMD64 machine as well, is that correct?

I believe that is correct.

**Comment by tariqislam** [comment]
@ayancey That worked, running on my Ubuntu machine. Thanks!
