### ISSUE TITLE
Combining with an external VAD or diarization

### ISSUE THREAD

**Issue by besimali** [ahmetoner/whisper-asr-webservice#25]
Start/End times of the segments are not always correct. Actually, the first segment always starts at the beginning of the file, even if it starts with a long silence. Apart from the timing being off, it can also cause the model to hallucinate a transcript, as it tries to transcribe this silence. 

This can be solved by doing the segmentation based on voice activity detection (VAD) first, and then using whisper to transcribe each segment.

While we are at it, we can even put [pyannote](https://github.com/pyannote/pyannote-audio) in the pipeline to support the full diarization.

**Comment by AustinSaintAubin** [comment]
Perhaps pulling from https://huggingface.co/spaces/vumichien/Whisper_speaker_diarization to get started with diarization.

**Comment by ayancey** [comment]
WhisperX integration is coming soon :)

**Comment by blundercode** [comment]
Is whisperX now available?
