### ISSUE TITLE
OpenAI Whisper large-v3-turbo model does not translate text

### ISSUE THREAD

**Issue by tariqislam** [ahmetoner/whisper-asr-webservice#250]
I have tried this model with a sample audio file (language was urdu). The response from the asr endpoint when task=translate is still in urdu.

**Comment by ayancey** [comment]
Can you provide more info about this? Was the same file working with whisper in the CLI?

**Comment by tariqislam** [comment]
[audio.mp3.zip](https://github.com/user-attachments/files/18120951/audio.mp3.zip)

Please see the attached zip file which contains one audio.mp3 file. This audio is in urdu. If you use the faster-whisper model (I ran it through docker + nvidia gpu) the translations/transcriptions work perfectly. However, if you use the openai large-v3-turbo model (again running through docker + nvidia gpu) and the API action is translate, it will only return transcribed text and will not do the translation.

I have not tried running it in the CLI.

**Comment by aidancrowther** [comment]
Have you validated that translation works with other models when using openai_whisper?

**Comment by ahmetoner** [comment]
#259
