### ISSUE TITLE
TypeError occurs when serializing Segments to JSON output format.

### ISSUE THREAD

**Issue by jwaring** [ahmetoner/whisper-asr-webservice#263]
Awesome project. Thank you @ahmetoner.

When using the output format set to 'json' and ASR_ENGINE is set to 'faster_whisper', with v1.7.0 I get a TypeError which indicates that the 'Segments' object is not Serializable. I was able to work around by changing the utils.WriteJSON method by using a custom JSON encoder.

```py
class JSONEncoder(json.JSONEncoder):
    def default(s, o):
        if dataclasses.is_dataclass(o):
            return dataclasses.asdict(o)
        return super().default(o)

class WriteJSON(ResultWriter):
    extension: str = "json"

    def write_result(self, result: dict, file: TextIO):
        json.dump(result, file, cls=JSONEncoder)
```

Not sure if this is the best approach so I didn't raise a PR. Specifically, the signature of the segment is different with my change, as  the segment is an object with field names such as start / end / tokens. In v1.6.0 a segment is an array one has to pluck the values from by index.

J

**Comment by ostpachukAndrii** [comment]
It seems that with the new release, they faster-whisper modified the response object, and now segments cannot be serialized using the previous approach. Unfortunately, Faster Whisper engine is currently not functioning as expected in release v1.7.0.
