### ISSUE TITLE
Posting a file via Swagger takes forever

### ISSUE THREAD

**Issue by yahorbarkouski** [ahmetoner/whisper-asr-webservice#27]
For some reason it takes forever to request for simple 3sec-duration file translation:
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/94449298/193948426-ec3c1a09-29ee-4010-869e-aebcb6b33939.png">
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/94449298/193948438-b7530fa8-3f96-4af2-a9af-fe5c38a53e1f.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/94449298/193948577-e35fcf87-e8aa-45aa-af0d-c79771c32015.png">
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/94449298/193948614-0a7d245c-47f0-4950-bf95-e5ff64d4cc82.png">

Is it ok for the first time?

**Comment by besimali** [comment]
Does it take forever (as in it does not finish) or it takes a really long time? Also, are the server and client on the same machine, or do you upload it via the internet?

**Comment by yahorbarkouski** [comment]
it took 10 mins to convert 3sec file from my end, server and the client on the same machine
