### ISSUE TITLE
GPU consumption at 100% all the time

### ISSUE THREAD

**Issue by lucasbr15** [ahmetoner/whisper-asr-webservice#28]
Good morning, now it is working with the mediu model,

However I'm a little confused

As I have zero knowledge about Docker,

But because when opening docker and starting the instance, I notice that the gpu consumption is almost at 100% intermittent usage,

So I would like to know if the VRAM is really being used, or is it just a (fake) virtualization?

![Screenshot_1](https://user-images.githubusercontent.com/97372669/194156908-7c332d7f-20f2-4bd4-9d83-bddc365421ac.png)

Thank you and I look forward to your reply;

Yours sincerely,
Lucas Rodrigues.

**Comment by besimali** [comment]
Hi Lucas, 

When you start the docker instance the server gets started automatically and when it does, it loads the model into working memory. Although the model is still not technically being used until you send a request, it is always loaded into memory as long as the server is up.  

So yes, the VRAM is really being used all the time.

Best,
Besim
