### ISSUE TITLE
Can't run on Ampere A100 40Gb

### ISSUE THREAD

**Issue by amessina71** [ahmetoner/whisper-asr-webservice#30]
Hi,
I'm trying to install the package on an Ampere A100 40GB system, using the default Dockerfile.gpu file.
The image gets built but when the container starts I get the following logs:
[...]
NVIDIA A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70
[...]

What/how do I have to modify to get it run on this environment?
many thanks ...

**Comment by mliradelc** [comment]
Here is a discussion about your issue;
https://stackoverflow.com/questions/66992585/how-does-one-use-pytorch-cuda-with-an-a100-gpu

Maybe you can modify the docker image to allow you to run Pytorch.

Have you check if you have the latest cuda installed?

**Comment by amessina71** [comment]
Hi, thanks for your reply. Here's an excerpt of the output of the nvidia-smi command:
Fri Oct 14 09:26:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
|   0  NVIDIA A100-PCI...  Off  | 00000000:17:00.0 Off |                    0 |
| N/A   64C    P0    91W / 250W |  35394MiB / 40960MiB |      0%      Default |
|   1  NVIDIA A100-PCI...  Off  | 00000000:65:00.0 Off |                    0 |
| N/A   36C    P0    49W / 250W |   5345MiB / 40960MiB |      0%      Default |

Looks like the Pytorch installation that gets included in the poetry project is not aligned with the underlying CUDA.
I guess this might be solved by changing a few lines in the configuration files but I'mnot that much familiar with poetry to make it myself.
Thank you in advance for your help
A.

**Comment by mliradelc** [comment]
Try to update cuda to 11.7, that works with my Quadro P4000
