### ISSUE TITLE
GPU out of memory issues

### ISSUE THREAD

**Issue by jshi361** [ahmetoner/whisper-asr-webservice#31]
Hi there,
Is there a way to limit the number of concurrent processes at the same time to prevent GPU out of memory error? For example we may use semaphore to limit the number of concurrent jobs

**Comment by ahmetoner** [comment]
Hi @jshi361,

My suggestion is using a queue mechanism such as RabbitMQ.  It allows you to create a semaphore service.
For more information: https://blog.rabbitmq.com/posts/2014/02/distributed-semaphores-with-rabbitmq

Greetings,
Ahmet
