### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by abdcef** [ahmetoner/whisper-asr-webservice#44]
I get this error message:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.`

**Comment by ahmetoner** [comment]
Hello @abdcef,

Thank you for reporting, could you please describe your environment? 

Distribution name and version (e.g. Ubuntu 18.10):
NVIDIA driver/Cuda version:
GPU (e.g. Asus Strix OC 1080 Ti):
Repository docker image version:
Docker run command: 

Ahmet

**Comment by abdcef** [comment]
Thanks. The run command was `docker run -d --gpus all -p 9000:9000 -e ASR_MODEL=base onerahmet/openai-whisper-asr-webservice:latest-gpu`
![CleanShot 2022-11-20 at 09 11 04@2x](https://user-images.githubusercontent.com/56148250/202877999-5f785337-00a5-4843-b6ff-a95755e45abb.png)
<img width="471" alt="CleanShot 2022-11-20 at 09 11 55@2x" src="https://user-images.githubusercontent.com/56148250/202878012-547c0f60-fa58-4a92-ad5e-384b1ac62a5d.png">

**Comment by reisub0** [comment]
GPU passthrough does not work on macOS due to fundamental design limitations of Docker. Docker actually runs containers within a LinuxVM on macOS. If you wish to run GPU-accelerated containers, I'm afraid Linux is your only option.

Cf. https://github.com/NVIDIA/nvidia-container-runtime/issues/133

**Comment by abdcef** [comment]
Thanks for letting me know
