### ISSUE TITLE
Queueing for parallel execution

### ISSUE THREAD

**Issue by jgorset** [ahmetoner/whisper-asr-webservice#50]
Hi @ahmetoner!

We found your nice web service while doing research for a project we're doing to make Whisper more accessible, where a web service is a necessary component. Thanks for making it and making it open source! We plan on doing that as well, and would be happy to share it with you in case its useful.

For our use case, we'd need the web service to be able to queue files for transcription, as many users may use it at once, and Whisper will hog the whole GPU and (as far as we know) crash upon trying to use VRAM that isn't available. If we can extend your web service to work off a queuing system, would you be inteterested in a pull request for that?

Best regards,
The speech to text team @Schibsted

**Comment by ahmetoner** [comment]
Hi @jgorset,

Thank you for your message. I was also planning for ASYNC request support and queue mechanism too. But please feel free to contribute this project. New contributions and pull requests are very welcomed from anyone. 

There is another thing I want to point out. As you notice before, the processing time takes very long time for big speech files. To solve that kind of issues, I plan to create another open source project (middleware) which will able to handle requests and split large audio files (with VAD functions) into small chunks. It will work/process simultaneously to achieve faster results with replicated services. Also this project will be able to run with another speech to text APIs ( Whisper, Kaldi, Google, AWS or private models etc.) with a UI (probably with AnguarJS) to check and compare results in a good interface. To sum up, new project will cover/solve _scaling_, _distributed jobs_, _high availability_, _single points of failure prevention_ for speech related apps. I know, I should share a road map. But I have limited time for now. Please stay tuned.

Best regards,
Ahmet
