### ISSUE TITLE
TARGETPLATFORM is not specified?

### ISSUE THREAD

**Issue by mcutshaw** [ahmetoner/whisper-asr-webservice#55]
When trying to build the dockerfile on my system I was running into the issue where the TARGETPLATFORM ARG was not populated and torch did not install, causing the container to successfully build, but immediately die once started. Unless there is something I am missing in regard the the TARGETPLATFORM ARG, then I would suggest that "--platform" be added to the documentation examples, and potentially install for torch for amd64 by default, as I have an unfounded assumption that platform is the more common for installs.

**Comment by ahmetoner** [comment]
Fixed in #71
