### ISSUE TITLE
Just A Note on Mac Torch Install

### ISSUE THREAD

**Issue by overkill864** [ahmetoner/whisper-asr-webservice#57]
On Mac, I couldn't get torch to install with the commands you had listed but modified the command to 
`pip3 install torch==1.13.0 -f https://download.pytorch.org/whl/torch` and it installed.

**Comment by Leafonix** [comment]
I am also having problems with installing torch. I'm on windows. None of the commands are working, and neither is the commands provided by the pytorch website.

**Comment by Leafonix** [comment]
> I am also having problems with installing torch. I'm on windows. None of the commands are working, and neither is the commands provided by the pytorch website.

Update: It turns out you need to have a version of python between 3.7.x and 3.9.x, I had python 3.11.x and it wasn't compatible.

**Comment by ahmetoner** [comment]
Fixed in #71
