### ISSUE TITLE
[FEATURE REQUEST] Translate into more than one language

### ISSUE THREAD

**Issue by fenpaws** [ahmetoner/whisper-asr-webservice#60]
I recently used your application and noticed that the translation feature only supports English. However, I have seen other wisper tools that can translate to multiple languages. I was wondering if it would be possible to add support for additional languages in the future?

It would be great if the application could support translation to any language it supports, this would greatly enhance the user experience and provide more flexibility.

Please let me know if this is something that can be implemented, and if there's any additional information that you need from me.

Thank you!

**Comment by ahmetoner** [comment]
The OpenAI Whisper AI model only supports translation from **Any Language to English**.

**Comment by ahmetoner** [comment]
See https://github.com/openai/whisper/discussions/649#discussioncomment-4325122
