### ISSUE TITLE
Request to include Faster-Whisper in API choices

### ISSUE THREAD

**Issue by RishishPandey** [ahmetoner/whisper-asr-webservice#79]
Hi,

I have been testing [Faster-Whisper](https://github.com/guillaumekln/faster-whisper), a library that claims to provide 4x faster inference than normal Whisper. After trying it out, I can confirm that it does seem to be faster.

I was wondering if it would be possible to include Faster-Whisper as a choice in your API? This would be beneficial for users who need faster inference times and would like to have the option to use Faster-Whisper.

Thank you for considering my request. Let me know if you need any additional information or have any questions.

Best regards,
Rishish Pandey

**Comment by ahmetoner** [comment]
closed by #81
