### ISSUE TITLE
Pinning poetry version

### ISSUE THREAD

**Issue by pjo256** [ahmetoner/whisper-asr-webservice#83]
The recently released 1.4.1 version of `poetry` exposes an issue with some dependencies where package hashes/sizes are marked as invalid and installation fails with `WheelFileValidationError`, e.g. `torch==1.12.0` - https://github.com/pytorch/pytorch/issues/97153

While this behavior can be disabled by setting `installer.modern-installation` to `false` (https://github.com/python-poetry/poetry/issues/7686) or downgrading from `1.4.1` to `1.4.0`, pinning `pip install poetry` in Dockerfiles seems like a good idea in case of other breaking changes in the future.

**Comment by ahmetoner** [comment]
closed by #82
