### ISSUE TITLE
Feature Request: Api key

### ISSUE THREAD

**Issue by peteh** [ahmetoner/whisper-asr-webservice#89]
It would be cool to add an api key. 

Use Case: 
host whisper and restrict access via api key. 

e.g. that an additional field can be set that is checked against the correct value, e.g. from en environment variable.

**Comment by ahmetoner** [comment]
Unfortunately, we don't have any plan to build this feature, so it will not support an API level key protection. There are several 3rd party solutions to achieve this purpose.

1. [nginxproxymanager](https://nginxproxymanager.com/) in front of [whisper-asr-webservice](https://github.com/ahmetoner/whisper-asr-webservice). (Easiest solution)
3. [apisix ](https://apisix.apache.org/) for the same purpose.
2. [Keycloak ](https://www.keycloak.org/) instance with a [nginx reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).  It will give bearer token support. 

If you need more support, you can send a private request email to me.
