### ISSUE TITLE
Roadmap for Intel QuickSync ?

### ISSUE THREAD

**Issue by garanda21** [ahmetoner/whisper-asr-webservice#90]
There's plans to support Intel's QuickSync acceleration ?

As a Synology owner with Celeron cpu and intel gpu, I'm interested in GPU hardware acceleration, like Plex container does.

Any chance to achieve that ?

**Comment by domrockt** [comment]
Yes that would be awsome, Unraid i9 12900 user here.

**Comment by avidenic** [comment]
Hi, would love this as well.

**Comment by ayancey** [comment]
QuickSync is afaik not related to tensors so this wouldn't be possible. Projects like whispercpp offer better CPU performance and we can hopefully implement that at some point.
