### ISSUE TITLE
GPUs that don't support float16?

### ISSUE THREAD

**Issue by kylrth** [ahmetoner/whisper-asr-webservice#94]
```
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

Is it going to be possible to run on my hardware?

**Comment by strike84** [comment]
Wondering the same thing. I have a GTX 1070 TI which does support float16, but at a low-rate.

**Comment by magico13** [comment]
Same with my GTX1060. It seems that only FasterWhisper is broken since I can pull v1.0.6-gpu and run that just fine but not the latest image.

**Comment by strike84** [comment]
Good to know it WAS working on the previous version. I just spun up this container last night so I was sure my GPU was the issue.

**Comment by ajatoledo** [comment]
Running into the same issue here; GPU is compatible with float16, reverting to `v1.0.6-gpu` and it works as expected.

**Comment by mkools** [comment]
Same issue here, 1.06 works. Glad I found this :)

**Comment by Clemens-E** [comment]
Same issue here, 1050TI 4GB, was previously working good widht nice speeds, now I updated and its reporting the same issue

**Comment by ahmetoner** [comment]
Could anyone please test `debug` image to verify GPU issue is gone?

`docker run -d --gpus all -p 9000:9000 -e ASR_MODEL=base onerahmet/openai-whisper-asr-webservice:debug-gpu`

**Comment by strike84** [comment]
Can confirm debug image is working. The option to choose faster-whisper is gone tho?

**Comment by kindziora** [comment]
can confirm current head still throws error, using faster_whisper:
`  File "/app/.venv/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 101, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
`

**Comment by Nikro** [comment]
In my case, I just changed to float32 and it worked. Maybe it'll help someone :)

```
diff --git a/app/faster_whisper/core.py b/app/faster_whisper/core.py
index aac9b10..72de2c1 100644
--- a/app/faster_whisper/core.py
+++ b/app/faster_whisper/core.py
@@ -14,7 +14,7 @@ model_path = os.path.join("/root/.cache/faster_whisper", model_name)
 model_converter(model_name, model_path)
 
 if torch.cuda.is_available():
-    model = WhisperModel(model_path, device="cuda", compute_type="float16")
+    model = WhisperModel(model_path, device="cuda", compute_type="float32")
```

**Comment by kylrth** [comment]
Amazing, the debug image works great!

**Comment by ahmetoner** [comment]
Hello y'all, [v1.1.1](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.1.1) has been released and it will be available on docker hub when GitHub pipeline finish.
