### ISSUE TITLE
Word level timing and confidence on json

### ISSUE THREAD

**Issue by blundercode** [ahmetoner/whisper-asr-webservice#95]
Hey there love the project just have a couple questions!

Just curious if you could offer word level timing and confidence scoring to the JSON. And would it be possible to integrate with something like whisperX or whisper-timestamped similar to the way you implemented the faster-whisper?

Whisper-Timestamped: https://github.com/linto-ai/whisper-timestamped
WhisperX: https://github.com/m-bain/whisperX

Cheers!

**Comment by blundercode** [comment]
@ahmetoner Any interest in these suggestions or should I work down a different route?

**Comment by ahmetoner** [comment]
Hello @blundercode, we will have new release soon with this feature.

**Comment by blundercode** [comment]
> Hello @blundercode, we will have new release soon with this feature.

@ahmetoner sounds good, let me know if I can help in anyway. Do you have an expected ETA for integration?

Love the project!

**Comment by blundercode** [comment]
I was actually able to implement it pretty easily, I am not a python developer so it is a little hacky. I will post how I implemented it in the morning.

**Comment by ahmetoner** [comment]
Actually Whisper started to provide word level timestamps (See [here](https://github.com/openai/whisper/blob/248b6cb124225dd263bb9bd32d060b6517e067f8/whisper/transcribe.py#L47)). But I was getting some error on triton side for different platforms. That's why I'm still pausing release process for this feature. I plan to publish this feature on this weekend.

**Comment by ahmetoner** [comment]
Hello [blundercode](https://github.com/blundercode), word timestamps feature is ready with Faster Whisper. You will be able to use new docker image when pipeline successfully finish. You can see the release notes [here](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.1.1).

**Comment by blundercode** [comment]
@ahmetoner Your a hero thank you so much I will test this out asap!
